name: Generate Animated Metrics

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the main branch
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate animated isometric calendar
        uses: lowlighter/metrics@latest
        with:
          filename: animated-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: output
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
